#!/bin/bash
./save-data no-name-given-to-save-data
rm -rf $SCRATCH/lilac_run_dir
cp -r ../rundir $SCRATCH/lilac_run_dir
cd $SCRATCH/lilac_run_dir
rm -rf output
mkdir output
mkdir output/stdout
mkdir output/stderr
qsub nersc_submit_script
